version: "3.9"
services:
  service_1:
    build: ./service_1
    container_name: service_1
    ports:
      - "8080:8080"
  
  service_2:
    build: ./service_2
    container_name: service_2
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - service_1
      - service_2