version: '3.8'
services:
  service_1:
    build: ./service_1
    ports:
      - "8080:80"
  service_2:
    build: ./service_2
    ports:
      - "5000:80"
    depends_on:
      - service_1
    environment:
      - SERVICE_1_URL=http://service_1:8080
  